export const FETCHING_ALBUMS = 'FETCHING_ALBUMS';
export const FETCHING_ALBUMS_SUCCESS = 'FETCHING_ALBUMS_SUCCESS';
export const FETCHING_ALBUMS_FAIL = 'FETCHING_ALBUMS_FAIL';

export const FETCHING_ALBUM = 'FETCHING_ALBUM';
export const FETCHING_ALBUM_SUCCESS = 'FETCHING_ALBUM_SUCCESS';
export const FETCHING_ALBUM_FAIL = 'FETCHING_ALBUM_FAIL';

export const FETCHING_PHOTOS = 'FETCHING_PHOTOS';
export const FETCHING_PHOTOS_SUCCESS = 'FETCHING_PHOTOS_SUCCESS';
export const FETCHING_PHOTOS_FAIL = 'FETCHING_PHOTOS_FAIL';

export const FETCHING_PHOTO = 'FETCHING_PHOTO';
export const FETCHING_PHOTO_SUCCESS = 'FETCHING_PHOTO_SUCCESS';
export const FETCHING_PHOTO_FAIL = 'FETCHING_PHOTO_FAIL';
