export const FETCHING_ALBUMS = 'FETCHING_ALBUMS';
export const FETCHING_ALBUMS_SUCCESS = 'FETCHING_ALBUMS_SUCCESS';
export const FETCHING_ALBUMS_FAIL = 'FETCHING_ALBUMS_FAIL';

export const FETCHING_PHOTOS = 'FETCHING_PHOTOS';
export const FETCHING_PHOTOS_SUCCESS = 'FETCHING_PHOTOS_SUCCESS';
export const FETCHING_PHOTOS_FAIL = 'FETCHING_PHOTOS_FAIL';
